server:
  port: 9006
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pair_prog?useSSL=false&serverTimezone=UTC
    username: root
    password: Veda@1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true